### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Tsamsiyu1** [raweee/node-red-contrib-whatsapp-link#1]
Hey can you write a little more info in how to use this?
i would love to use it but i cant even know how to get the QR code to work.
Thanks

**Comment by Teme-V** [comment]
Just found this and have same issue - appreciate to have a bit more instruction included
Thank you

**Comment by raweee** [comment]
Sorry for inconvenience.
I appreciate your suggestions, detailed info will their within a day.
