### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'evaluate')

### ISSUE THREAD

**Issue by renants286** [raweee/node-red-contrib-whatsapp-link#11]
Hello,
I changed my plans after Connecting Error and now I'm running node-red in a virtual machine. After one day running OK, with all nodes updated, today after a Node-red Deploy, WhatsApp-link crashed again. Follow the error.

![image](https://user-images.githubusercontent.com/122543436/213160390-545d3d89-230e-4b28-8443-15a154591329.png)

Any tip about it?

**Comment by raweee** [comment]
This might be due to slow working of whatsappLink node. Try again it will work
