### ISSUE TITLE
Button Messages in WhatsApp Web

### ISSUE THREAD

**Issue by ryangonzalez133** [raweee/node-red-contrib-whatsapp-link#15]
Hello, Any way to make messages by button work in whatsapp-web?

**Comment by raweee** [comment]
Working on it, it will take a bit of time.

**Comment by ryangonzalez133** [comment]
Hello Vasco greetings. Do you have any predictions for the operation of button messages in web socket?

**Comment by ryangonzalez133** [comment]
hello, the message lists or button is not visible on mobile whatsapp, only on whatsapp web. on the cell phone it seems that you have not received any new messages. it is only visible through the web. do you know what it could be?

**Comment by jjcampis** [comment]
> hello, the message lists or button is not visible on mobile whatsapp, only on whatsapp web. on the cell phone it seems that you have not received any new messages. it is only visible through the web. do you know what it could be?

I wnat to know that too.. i´m investigating
