### ISSUE TITLE
WhatsApp Node-RED Location

### ISSUE THREAD

**Issue by treshanappuhamy** [raweee/node-red-contrib-whatsapp-link#17]
If someone sends you a live location, can we use node red to locate WhatsApp location to node track it?

**Comment by raweee** [comment]
Yes location can be recieved using Chats-In Node at `msg.message.locationMessage.degreesLatitude` and `msg.message.locationMessage.degreesLongitude` 
these geo values can further use to determine the location.

**Comment by treshanappuhamy** [comment]
hello, thanks for the reply, when I send a live location and check the msg.message contents there is no variable called locationMessage.degreeLatitude. there is however a body with the image of the live location showing where I am but no exact coordinates, is there a way to get some help with this. 

Thanks a lot for your help.

**Comment by raweee** [comment]
Hi @treshanappuhamy,
Which client you are using in`whatsapp-link` node.
What I told you above is the output of whatsapp-line client.
You may explore `msg.message` to get all the information received in WhatsApp message

**Comment by treshanappuhamy** [comment]
I think the live location payload sent is onetime cause even though i share a live location it shows as a static location. it doesn't update when the client whatsappp user moves. Any Advice for this?
