### ISSUE TITLE
Error creating whatsapp lite 

### ISSUE THREAD

**Issue by ryangonzalez133** [raweee/node-red-contrib-whatsapp-link#19]
When creating the whatsapp lite user, the error 
"Error: Cannot find module 'pino' is returned in the debug
Require stack:
- /data/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js" and 
"TypeError: Cannot read properties of null (reading 'client')"

**Comment by raweee** [comment]
Hello brother,
Please update the node and it will work fine. If their was still a problem.
