### ISSUE TITLE
whatsapp-link crash node-red

### ISSUE THREAD

**Issue by Teme-V** [raweee/node-red-contrib-whatsapp-link#2]
After adding whatsapp-admin node and injecting message, node-red will creash
I'm running node-red docker in headless linux server 
Using latest Version: 0.1.15 of whatsapp-link

node-red  | Welcome to Node-RED
node-red  | ===================
node-red  | 
node-red  | 6 Dec 22:15:01 - [info] Node-RED version: v3.0.2
node-red  | 6 Dec 22:15:01 - [info] Node.js  version: v16.16.0
node-red  | 6 Dec 22:15:01 - [info] Linux 5.10.0-18-amd64 x64 LE
node-red  | 6 Dec 22:15:01 - [info] Loading palette nodes
node-red  | 6 Dec 22:15:03 - [info] Dashboard version 3.2.0 started at /ui
node-red  | 6 Dec 22:15:03 - [warn] ------------------------------------------------------
node-red  | 6 Dec 22:15:03 - [warn] [node-red-contrib-data-logger/data-logger] Error: Cannot find module '/data/node_modules/node-red-contrib-data-logger/.\src\data-logger.js'
node-red  | Require stack:
node-red  | - /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
node-red  | - /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
node-red  | - /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
node-red  | - /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
node-red  | - /usr/src/node-red/node_modules/node-red/lib/red.js
node-red  | - /usr/src/node-red/node_modules/node-red/red.js
node-red  | 6 Dec 22:15:03 - [warn] ------------------------------------------------------
node-red  | 6 Dec 22:15:03 - [info] Settings file  : /data/settings.js
node-red  | 6 Dec 22:15:03 - [info] Context store  : 'file' [module=localfilesystem]
node-red  | 6 Dec 22:15:03 - [info] Context store  : 'default' [module=memory]
node-red  | 6 Dec 22:15:03 - [info] User directory : /data
node-red  | 6 Dec 22:15:03 - [warn] Projects disabled : editorTheme.projects.enabled=false
node-red  | 6 Dec 22:15:03 - [info] Flows file     : /data/flows.json
node-red  | 6 Dec 22:15:03 - [info] Server now running at http://127.0.0.1:1880/
node-red  | 6 Dec 22:15:03 - [warn] 
node-red  | 
node-red  | ---------------------------------------------------------------------
node-red  | Your flow credentials file is encrypted using a system-generated key.
node-red  | 
node-red  | If the system-generated key is lost for any reason, your credentials
node-red  | file will not be recoverable, you will have to delete it and re-enter
node-red  | your credentials.
node-red  | 
node-red  | You should set your own key using the 'credentialSecret' option in
node-red  | your settings file. Node-RED will then re-encrypt your credentials
node-red  | file using your chosen key the next time you deploy a change.
node-red  | ---------------------------------------------------------------------
node-red  | 
node-red  | 6 Dec 22:15:03 - [info] Starting flows
node-red  | 6 Dec 22:15:03 - [info] [whatsappLink:Web] Status : Initializing Whatsapp..
node-red  | 6 Dec 22:15:03 - [info] Started flows
node-red  | 6 Dec 22:15:03 - [error] Error: Failed to launch the browser process! spawn /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome ENOENT
node-red  | 
node-red  | 
node-red  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
node-red  | 
node-red  |     at onClose (/data/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
node-red  |     at ChildProcess.<anonymous> (/data/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
node-red  |     at ChildProcess.emit (node:events:527:28)
node-red  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
node-red  |     at onErrorNT (node:internal/child_process:478:16)
node-red  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
node-red exited with code 1

**Comment by raweee** [comment]
WhatsApp link require chromium in background to connect and control whatsapp. In your case Puppeteer is not able to launch chromium. Possible reasons might be-
- node was not installed correctly (chromium)
- some libraries are missing in linux.
Currently working on it, I'll let you know the status.

**Comment by raweee** [comment]
Crashing for Node-Red was fixed. Try now..
but you need to update your system also.

**Comment by Teme-V** [comment]
I have installed chromium to my system, but unfortunately result was exactly same. 
 All configs very basic

**Comment by raweee** [comment]
$ sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

These are the dependencies, Update all if any missing will install. 
No need to install chromium.
