### ISSUE TITLE
Client name in configuration and profile dir

### ISSUE THREAD

**Issue by odv1983** [raweee/node-red-contrib-whatsapp-link#23]
Hi, please add client name to client configuration and add the parameter bellow to args in puppeteer, this will able to connect more clients, based in Chromium profiles.

'--user-data-dir=/user/data/directory/profile_n'
To help: https://stackoverflow.com/questions/53236692/how-to-use-chrome-profile-in-puppeteer

**Comment by raweee** [comment]
Multiple user profile will mix all the messages.
