### ISSUE TITLE
"Error Sending Msg:: TypeError: numb.replace is not a function"

### ISSUE THREAD

**Issue by alex-shape** [raweee/node-red-contrib-whatsapp-link#26]
Hi guys, 

I recently updated to version 0.1.36-A and the Chats Out node drops the error "Error Sending Msg:: TypeError: numb.replace is not a function",

Here is the `msg` object `Chat Out` node is receiving
```
object
payload: "The device is online"
toNumber: array[1]
0: "+xxxxxxxxxxxxx"
```

Thank you very much

**Comment by raweee** [comment]
Number might be in not correct manner

**Comment by alex-shape** [comment]
Hi, 

I am sorry to insist, but it worked with previous versions, something with the update is caused this issue.

The format how the previous node is passing the phone numbers is the next one: 

`msg.toNumber = ["+XX1234567890","+XX1234567891"]`

where `XX` is the country code, `1234567890` and `1234567891` are the numbers.

This is the msg received by `Chats Out` node:

```
object
payload: "The device is online"
_msgid: "fa4b060c9b0d3c38"
toNumber: array[2]
0: "+XX1234567890"
1: "+XX1234567891"
```

If I put `+XX1234567890, XX1234567891` at `Chats Out` number field neither works

It only works if I put `XX1234567890` or `XX1234567891` at `Chats Out` number field.

It does not accept incoming numbers in `msg` (both as the example or just one number) to send the message.

I want to thank you for your dedication and want to apologize as I cannot help you more, just providing my detailed experience using your nodes, hope this helps you.

Thanks again.

**Comment by alex-shape** [comment]
Update:

If it receives just one number formatted as `'XX1234567890'` it works too,  with an array it does not.

Thank you.

**Comment by raweee** [comment]
Hi @alex-shape, thanks for detailed bug,
due to some error it was not able to detect Array and consider that Array as an string. 

Fixed now, Thanks
