### ISSUE TITLE
Message lists or button

### ISSUE THREAD

**Issue by ryangonzalez133** [raweee/node-red-contrib-whatsapp-link#28]
hello, the message lists or button is not visible on mobile whatsapp, only on whatsapp web. on the cell phone it seems that you have not received any new messages. it is only visible through the web. do you know what it could be?

**Comment by raweee** [comment]
I was away, let me see and correct it if it was.

**Comment by ryangonzalez133** [comment]
welcome again my friend, I was already missing the whatsapp improvements

**Comment by ryangonzalez133** [comment]
Friend, I think the update did not solve the problem. Is it on my side or on the knot?

**Comment by jjcampis** [comment]
> hello, the message lists or button is not visible on mobile whatsapp, only on whatsapp web. on the cell phone it seems that you have not received any new messages. it is only visible through the web. do you know what it could be?

same problem here... i was seeing nothing, but then i opened whatsapp web... and the buttons was there :) but only on web... not on mobile

**Comment by ryangonzalez133** [comment]
I think that in some whatsapp update they removed some support for this type of message. probably the code for this message is another and we don't know

**Comment by raweee** [comment]
Form latest whatsapp update, whatsapp try to block buttons and lists from all other sources (server side) and only official whatsapp apis are allowed to send these type of messages. Some of my friends are already working on it to bypass this situation. 

I'll update the Nodes here as soon as it possible.
