### ISSUE TITLE
Can't download the palette 

### ISSUE THREAD

**Issue by morshed409** [raweee/node-red-contrib-whatsapp-link#29]
Hi,
I am facing problem installing the palette. It is showing this message-  
" npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!"

can you please help me out?

**Comment by raweee** [comment]
This error is related to node.js and dependencies

**Comment by raweee** [comment]
You need to update all
