### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'client')

### ISSUE THREAD

**Issue by zachsa999** [raweee/node-red-contrib-whatsapp-link#31]
This looks like a cool project. I can't get anything to work. 

Its installed, when I deploy all I get is the error 
`TypeError: Cannot read properties of null (reading 'client')`

**Comment by zachsa999** [comment]
That wasn't detailed enough. Its the error message was output by the WAAdmin node.

![image](https://user-images.githubusercontent.com/56491639/227661177-4e7012a5-7cf9-484b-b903-da92ec243580.png)

**Comment by ryangonzalez133** [comment]
are you testing the lite version?

**Comment by raweee** [comment]
That was not suppose to do, can you explain your procedure.

**Comment by raweee** [comment]
Your node might be not installed correctly
