### ISSUE TITLE
Group Messages Time Out

### ISSUE THREAD

**Issue by JohnnyBreslin** [raweee/node-red-contrib-whatsapp-link#35]
Hi,

Running whatsapp lite and all going great except group messages which never work. I have tried "!nodered" and my own test groups but always just 'Error Sending Msg:: Error: Timed Out'.  If I can add any further info just shout, running NR 3.0.2 under docker on Synology NAS.

Thanks,
Johnny

**Comment by raweee** [comment]
Hi,
Please try.
In chats-out node. Try group number instead of mobile number. 
Chats-out node will detect the group and try to send your msz.
Let me know the result.

**Comment by irqnet** [comment]
chats-out node same problem:

"Error Sending Msg:: Error: Timed Out"
`12 Oct 11:29:33 - [error] [chats-out:Chats Out] Error Sending Msg:: Error: Timed Out`
