### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by Tsamsiyu1** [raweee/node-red-contrib-whatsapp-link#42]
TypeError: data.id.id.substring is not a function
0|node-red  |     at Message._patch (/home/marcel/.node-red/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
0|node-red  |     at new Message (/home/marcel/.node-red/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
0|node-red  |     at Client.sendMessage (/home/marcel/.node-red/node_modules/whatsapp-web.js/src/Client.js:699:16)
0|node-red  |     at runMicrotasks (<anonymous>)
0|node-red  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AlejandroFM-Github** [comment]
Same here. Recently, **[whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)** was updated. I already install this update; however, problem remains in node-red. Thank you in advance for your help!

**Comment by raweee** [comment]
Working now to text receive/send.

**Comment by raweee** [comment]
Whatsapp Send and Receive working fine now.
