### ISSUE TITLE
Stopped working from 07-06-2023

### ISSUE THREAD

**Issue by nabinz** [raweee/node-red-contrib-whatsapp-link#43]
I have been using this node for the last two months and it was working like a charm but from 07-06-2023. The QR code is getting generated but when scanning it to log in it's not getting authenticated and when injecting the "test" probe to check the availability it shows presence available but not getting connected.  I have tested it on a fresh machine with a new Node-red installation and still faced the same issue. Looking forward to seeing this issue fixed and resume playing with the node

**Comment by jesusmarcos** [comment]
Same here. In my case, it's not able to connect and also restarts node-red continuously.

I'm using the lite version.

Any help will be appreciated.

**Comment by nabinz** [comment]
Yes. I am running node-red on a docker container and the node-red is unable to restart after trying to connect the Whatsapp admin node

**Comment by Alexnator1989** [comment]
Have the same problem. QR code is output, Whatsapp also recognizes it as a QR code. After a minute Whatsapp says that the connection is broken. You can see briefly in the first few seconds after the scan that the node tries to connect and then jumps directly to "Disconnected". After that, no more QR code is generated until you delete the "Whatsapp-Link" folder under the node-red folder. Then the session is generated again. But even then the connection with the new QR code does not work.

**Comment by nabinz** [comment]
Yes facing the same issue. Trying to get a response from the developer so that we may be able to collaborate to solve the issue. This node was one of the favorite node in Node-red

**Comment by ryangonzalez133** [comment]
For those who want to continue using whatsapp at least with the basics until there is a new update, just use the WEB mode that is working, but unfortunately for some the WEB crashes the node-red, so just do it like this

 "So I installed node-red via docker separate from the Home assistant, at first it gave an error, so I installed puppeteer directly in the docker that worked fine doing this.
Run the command:

docker exec -it --user=root node-red /bin/sh

After entering your node-red docker file, a "node-red" folder will appear but at least for me, this is not the correct node-red folder, so you have to access where the node-red folder really is red, mine is in "/data/noderyan". So just "cd" to go back to the folders and find the right one, then run the following commands

`
apk update

apk add --no-cache chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main

rm /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome

ln -s /usr/bin/chromium-browser /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
`
Use all commands with docker running.

So it worked fine, it doesn't ask to connect again with whatsapp and so far it hasn't given any errors, I'm using web, lite was giving an error all the time and when I restarted I had to connect again. "

after installing the file that was the reason for the crash, it does not happen again and it is possible to receive and send messages through whatsapp on node-red

**Comment by Alexnator1989** [comment]
Wow! Thank you very much!
That actually helped that now the web connector works. Before that, from the moment you deployed the web connector, it was all over. The container was always down and couldn't be started anymore. Now this also happens from time to time after a deploy, but you can start up again, a QR code is generated with which you can now also connect with Whatsapp. 
Perfect!

**Comment by nabinz** [comment]
I have tried to implement the solution provided by @ryangonzalez133 but for that, I am unable to install puppeteer directly in the docker  can anyone have any idea about how to do that

**Comment by ryangonzalez133** [comment]
Worst of all, I don't remember how I installed it. But I think node-red-contrib-whatsapp-link itself adds puppeteer. Try to add the WEB and connect to your whatsapp, if node-red keeps crashing, you enter the flows.json file and delete the line of code that looks like this 
" {
        "id": "139f776b4e",
        "type": "whatsappLink",
        "cName": "whatsapp-web",
        "name": "Web",
        "clientType": "waWebClient",
        "onlineStatus": true,
        "loopTime": "1"
    },". 
Save, restart node-red and check if puppeteer was not installed

**Comment by JosepFarreLlados** [comment]
Thank you very much! Works perfect Whatsapp Web using Synology DSM v7.2-64570 in the Container Manager v20.10.23-1413. 
Any experience when the container is update? Is necessary do again the [ryangonzalez133](https://github.com/ryangonzalez133) update?

**Comment by ryangonzalez133** [comment]
this I don't know how to tell. I think that while connected to whatsapp, it will continue to run, as I only needed to update when I started using the lite version and stopped using the web.

**Comment by raweee** [comment]
Fixed
