### ISSUE TITLE
Chat Out, receiver number

### ISSUE THREAD

**Issue by yaseralie** [raweee/node-red-contrib-whatsapp-link#5]
Thank you for creating this awesome node,
I just have a request, could you change the chat out node?
Change Number in node is not fix, we can send the number from msg, for example msg.number for the number, and msg.payload for the message

Thank You

**Comment by raweee** [comment]
Working on it 👍

**Comment by raweee** [comment]
Updated in `msg.toNumber` from `Ver-0.1.30`.
