### ISSUE TITLE
msg.toNumber

### ISSUE THREAD

**Issue by PincoPanco** [raweee/node-red-contrib-whatsapp-link#60]
msg.to number : how to

**Comment by PincoPanco** [comment]
Hi to all
Please can you help me to understand the use of msg.toNumber statement in payload whit an example?
thanks for your cooperation

**Comment by fabosan** [comment]
Here an example to import in node-red.
[
    {
        "id": "b9bb22005361891e",
        "type": "inject",
        "z": "99aef0fd15a94c9c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 660,
        "wires": [
            [
                "28c1bd61bd747953"
            ]
        ]
    },
    {
        "id": "28c1bd61bd747953",
        "type": "function",
        "z": "99aef0fd15a94c9c",
        "name": "function 95",
        "func": "msg.toNumber = [\"+59899397541\"]\nmsg.payload = \"hola desde nodered\"\nreturn msg;\n\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 130,
        "y": 580,
        "wires": [
            [
                "5f4bc48f1c94b17d"
            ]
        ]
    },
    {
        "id": "5f4bc48f1c94b17d",
        "type": "function",
        "z": "99aef0fd15a94c9c",
        "name": "Enviar WhatsApp",
        "func": "// Obtener el número de teléfono del mensaje de entrada\nconst toNumbers = msg.toNumber || config.toNumber;\n\n// Verificar si se proporcionó un solo número o una matriz de números\nconst numbers = Array.isArray(toNumbers) ? toNumbers : [toNumbers];\n\n// Mensaje a enviar\nconst payload = msg.payload;\n\n// Imagen en base64 y leyenda (si está presente)\nconst image = msg.image;\nconst caption = msg.payload;\n\n// Enviar mensaje a cada número de teléfono\nnumbers.forEach(async number => {\n    try {\n        if (image) {\n            // Si hay una imagen, enviar un mensaje multimedia\n            await whatsappMultiMediaMessage(number, image, caption);\n        } else {\n            // Si no hay imagen, enviar un mensaje de texto\n            await whatsappMessage(number, payload);\n        }\n    } catch (error) {\n        node.error(`Error al enviar mensaje a ${number}: ${error}`);\n    }\n});\n\n// Función para enviar un mensaje de WhatsApp\nasync function whatsappMessage(number, message) {\n    // Lógica para enviar un mensaje de texto a través del nodo de WhatsApp\n}\n\n// Función para enviar un mensaje multimedia de WhatsApp\nasync function whatsappMultiMediaMessage(number, image, caption) {\n    // Lógica para enviar un mensaje multimedia a través del nodo de WhatsApp\n}\n\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 350,
        "y": 580,
        "wires": [
            [
                "7e293adf13f85d15"
            ]
        ]
    },
    {
        "id": "7e293adf13f85d15",
        "type": "chats-out",
        "z": "99aef0fd15a94c9c",
        "name": "Chats Out",
        "whatsappLink": "6e3c3360a6ec5da4",
        "number": "",
        "x": 540,
        "y": 600,
        "wires": []
    },
    {
        "id": "6e3c3360a6ec5da4",
        "type": "whatsappLink",
        "cName": "whatsapp-web",
        "name": "Web",
        "clientType": "waWebClient",
        "onlineStatus": true,
        "loopTime": "5"
    }
]

**Comment by fabosan** [comment]
Here an example to import in node-red.

[
    {
        "id": "b9bb22005361891e",
        "type": "inject",
        "z": "99aef0fd15a94c9c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 660,
        "wires": [
            [
                "28c1bd61bd747953"
            ]
        ]
    },
    {
        "id": "28c1bd61bd747953",
        "type": "function",
        "z": "99aef0fd15a94c9c",
        "name": "function 95",
        "func": "msg.toNumber = [\"+1111111111111\"]\nmsg.payload = \"hola desde nodered\"\nreturn msg;\n\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 130,
        "y": 580,
        "wires": [
            [
                "5f4bc48f1c94b17d"
            ]
        ]
    },
    {
        "id": "5f4bc48f1c94b17d",
        "type": "function",
        "z": "99aef0fd15a94c9c",
        "name": "Enviar WhatsApp",
        "func": "// Obtener el número de teléfono del mensaje de entrada\nconst toNumbers = msg.toNumber || config.toNumber;\n\n// Verificar si se proporcionó un solo número o una matriz de números\nconst numbers = Array.isArray(toNumbers) ? toNumbers : [toNumbers];\n\n// Mensaje a enviar\nconst payload = msg.payload;\n\n// Imagen en base64 y leyenda (si está presente)\nconst image = msg.image;\nconst caption = msg.payload;\n\n// Enviar mensaje a cada número de teléfono\nnumbers.forEach(async number => {\n    try {\n        if (image) {\n            // Si hay una imagen, enviar un mensaje multimedia\n            await whatsappMultiMediaMessage(number, image, caption);\n        } else {\n            // Si no hay imagen, enviar un mensaje de texto\n            await whatsappMessage(number, payload);\n        }\n    } catch (error) {\n        node.error(`Error al enviar mensaje a ${number}: ${error}`);\n    }\n});\n\n// Función para enviar un mensaje de WhatsApp\nasync function whatsappMessage(number, message) {\n    // Lógica para enviar un mensaje de texto a través del nodo de WhatsApp\n}\n\n// Función para enviar un mensaje multimedia de WhatsApp\nasync function whatsappMultiMediaMessage(number, image, caption) {\n    // Lógica para enviar un mensaje multimedia a través del nodo de WhatsApp\n}\n\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 350,
        "y": 580,
        "wires": [
            [
                "7e293adf13f85d15"
            ]
        ]
    },
    {
        "id": "7e293adf13f85d15",
        "type": "chats-out",
        "z": "99aef0fd15a94c9c",
        "name": "Chats Out",
        "whatsappLink": "6e3c3360a6ec5da4",
        "number": "",
        "x": 540,
        "y": 600,
        "wires": []
    },
    {
        "id": "6e3c3360a6ec5da4",
        "type": "whatsappLink",
        "cName": "whatsapp-web",
        "name": "Web",
        "clientType": "waWebClient",
        "onlineStatus": true,
        "loopTime": "5"
    }
]

**Comment by PincoPanco** [comment]
Many thanks!
It's work
Have you a nice day

**Comment by PincoPanco** [comment]
Thanks for support
:-)
