### ISSUE TITLE
QR Issue

### ISSUE THREAD

**Issue by gbravery** [raweee/node-red-contrib-whatsapp-link#7]
Similar to the currently open QR code issue, and the other issue that is closed.
I've tried to get this working, and it crashes my node-red server (the error is very similar, if not identical to the closed one).

I'm remote from the server that is running node-red (its actually in a docker).
Will your module work in my situation, or do I need to be directly connected to see the pop up, and scan the QR Code?

Thanks in advance

**Comment by raweee** [comment]
Hi,
If node-red is crashing,
In docker their are might be some lib are missing, you may update them -- 
`$ sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

Just copy and paste this in your terminal and restart. it will work. 
or 
if you able to show the error, it might works.

**Comment by gbravery** [comment]
Interestingly, I just tried this one:
node-red-contrib-kore-whatsappbot
And it did show me the QRCode... 

Although I have no idea what the differences are between the two development approaches being used between the two projects...
